apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    entrypoint:
    - ""
    command:
    - sleep
    args:
    - infinity
  - name: helm
    image: registry.internal.unified-streaming.com/operations/kubernetes/helm-kubectl/trunk:latest
    command:
    - sleep
    args:
    - infinity
  - name: crane
    image: gcr.io/go-containerregistry/crane:debug
    entrypoint: 
    - ""
    command:
    - sleep
    args:
    - infinity
  - name: docker-pushrm
    image: registry.internal.unified-streaming.com/operations/base-images/docker-pushrm/trunk:latest
    entrypoint: 
    - ""
    command:
    - sleep
    args:
    - infinity 
  imagePullSecrets:
  - name: gitlab-registry